export enum Method {
  UMBRAL_V1_GET_PUBLIC_KEY = 1,
  UMBRAL_V1_GET_SIGNING_KEY,
  UMBRAL_V1_ENCRYPT,
  UMBRAL_V1_GENERATE_KEY_FRAGMENTS,
  UMBRAL_V1_DECRYPT,
  UMBRAL_V1_DECRYPT_REENCRYPTED,
  UMBRAL_V1_VERIFY_CAPSULE_FRAGMENT,
}
