const TX_INTERPRETER_URL_PREFIX_BY_BECH32_PREFIX: Record<string, string> = {
  agoric: "agoric",
  atomone: "atomone",
  akash: "akash",
  axelar: "axelar",
  babylon: "babylon",
  bostrom: "bostrom",
  celestia: "celestia",
  chihuahua: "chihuahua",
  cosmos: "cosmoshub",
  cro: "cryptoorgchain",
  dydx: "dydx",
  elys: "elys",
  iaa: "irisnet",
  jkl: "jackal",
  juno: "juno",
  kava: "kava",
  kyve: "kyve",
  lava: "lava",
  like: "likecoin",
  lumera: "lumera",
  milk: "milkyway",
  mantra: "mantra",
  neutron: "neutron",
  nillion: "nillion",
  noble: "noble",
  nolus: "nolus",
  omniflix: "omniflix",
  osmo: "osmosis",
  pasg: "passage",
  persistence: "persistence",
  pokt: "pocket",
  pryzm: "pryzm",
  quick: "quicksilver",
  regen: "regen",
  saga: "saga",
  secret: "secretnetwork",
  seda: "seda",
  sent: "sentinel",
  somm: "sommelier",
  stars: "stargaze",
  stride: "stride",
  terra: "terra2",
  thor: "thorchain",
  umee: "umee",
  union: "union",
  xion: "xion",
};

export function getTxInterpreterURLPrefix(bech32Prefix: string) {
  return TX_INTERPRETER_URL_PREFIX_BY_BECH32_PREFIX[bech32Prefix] ?? "";
}
